name: tokuapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/colors/
    - assets/images/family_members/
    - assets/images/numbers/
    - assets/sounds/colors/
    - assets/sounds/family_members/
    - assets/sounds/phrases/
    - assets/sounds/numbers/
